# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18pfsSbQRXLeiEjuuEvfkePIaby9Kl4Ed
"""

def tbc_screening():
    print("Selamat datang di Aplikasi Skrining TBC")
    print("Silakan jawab beberapa pertanyaan untuk menentukan Indikasi Anda terkena TBC.")

    # Pertanyaan pertama
    answer1 = input("1. Apakah Anda saat ini sedang batuk lebih dari 2 minggu? (ya/tidak): ").strip().lower()

    # Pertanyaan kedua
    answer2 = input("2. Apakah anda berkeringat di malam hari tanpa sebab? (ya/tidak): ").strip().lower()

    # Pertanyaan ketiga
    answer3 = input("3. Apakah Anda mengalami demam lebih dari 2 minggu? (ya/tidak): ").strip().lower()

    # Pertanyaan keempat
    answer4 = input("4. Apakah anda mengalami turunnya berat badan yang drastis? (ya/tidak): ").strip().lower()

    # Pertanyaan kelima
    answer5 = input("5. Apakah anda memiliki kontak erat dengan pasien TBC? (ya/tidak): ").strip().lower()

    # Logika tambahan
    if answer1 == "ya" and answer2 == "ya" and answer3 == "ya" and answer4 == "ya":
        print("Anda memiliki gejala TBC berdasarkan jawaban Anda.")
        return "Rujukan ke Fasyankes terdekat"

    # Jika tidak ada tanda-tanda TBC dari pertanyaan 1 sampai 4, namun jawaban pertanyaan 5 adalah "ya"
    elif answer5 == "ya":
        print("Anda memiliki kontak erat dengan pasien TBC")
        return "Rujukan ke Fasyankes terdekat"

    # Jika tidak ada gejala yang mencurigakan
    print("Anda tidak memiliki tanda-tanda risiko TBC berdasarkan jawaban Anda kecuali kontak erat dengan pasien TBC.")
    return "Rujukan ke Fasyankes terdekat"

if __name__ == "__main__":
    hasil_skrining = tbc_screening()
    print(f"Hasil Skrining TBC: {hasil_skrining}")
